### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by melflynn** [vernchao91/Echo#1]
- [x] Need to have 7 total MVPs. Usually for discord we would add a "live" messaging MVP where users can see messages update live as they are sent without having to refresh the page

**Comment by vernchao91** [comment]
completed 7 MVPs and also a bonus if I have time!

**Comment by melflynn** [comment]
Looks good! I would switch the order live chat and conversations MVPs, just so that you have my support when you start trying to implement action cable and websockets in case things take longer than anticipated! (websockets will get implemented in the live chat portion)
