### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by melflynn** [vernchao91/Echo#2]
- [x] Table names should always be plural nouns. i.e. "messaging" should be "messages"
- [x] For messages table, you probably don't need the server_id, since that can be derived from the channel. Let me know if you have another reasoning for including it
- [x] ^ Make sure that you index foreign keys! (author_id on messages table)
- [x] You may want to think about how you can track which users are in which channels

**Comment by vernchao91** [comment]
changed table names to plural,
took away the server_id for messages table,
indexed all foreign keys
added a joins table called "lists". keeps track of users in each server
