### ISSUE TITLE
Server MVP

### ISSUE THREAD

**Issue by vernchao91** [vernchao91/Echo#7]
# Server MVP
## Functionality
- [x] Should be able to Create Server
- [x] Should display list of users on server
- [x] Should display server name on server
- [x] Should display channels list on server( placeholder for now)
### Public Server
- [x] Should be able to Join Server
- [x] Should be able to Leave Server
### Owner of Server
- [x] Should be able to Edit or Delete Server
## Style
- [x] The elements are positioned correctly on the page
- [ ] Remove Redux logger and all console.log()'s from production
## Seeds
- [x] Adequate and appropriate seeds

**Comment by melflynn** [comment]
- [x] should redirect to the /app page upon logging in
- [x] shouldn't be able to click to join a server you have already joined
- [x] if you are going to make all servers public, you should probably have some sort of separation in your list to show which servers you are a member of, and which you are not
- [x] The create server button only opens the modal if you click directly on the plus character. Should probably change it to be able to click the whole box
- [x] Edit server box should prepopulate with the current servers name
- [x] should see an error when trying to create a server which already exists

**Comment by vernchao91** [comment]
redirects to `/app` page after login
leave/delete server buttons redirects to `/app`
changed so owner cant leave the server, only delete it
only join server or leave server will display
create server button enlarged to div container
 edit server box populates field
error handling for create server finished
